spring.application.name=projet-web
server.port=8090
# Configuration of the SGBD SQLite
spring.datasource.url=jdbc:sqlite:db/sport.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
# Configuration of Hibernate
spring.jpa.databaseplatform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# TMDB
tmdb.api-key=feee0865f7a91c5cb1cae7aaef55f4cc
tmdb.base-url=http://api.openweathermap.org/data/2.5