name: SonarQube et Javadoc CI

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build, analyze and check
    runs-on: ubuntu-latest
    steps:
      # Étape 1 : Récupérer le code avec l'historique complet 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      # Étape 2 : Configurer JDK 17 
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'

      # Étape 3 : Mettre en cache les paquets SonarQube 
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Étape 4 : Mettre en cache les paquets Maven 
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Étape 5 : Compiler et tester le projet
      - name: Build and Test
        run: mvn -B clean verify

      # Étape 6 : Vérifier la conformité de la Javadoc 
      - name: Check Javadoc
        run: mvn javadoc:javadoc -DfailOnError=true

      # Étape 7 : Analyser avec SonarQube et attendre le résultat
      - name: SonarQube Analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ArijHadda_sharePortfolioMiageIndistrualisationTP3 -Dsonar.qualitygate.wait=true
